### ISSUE TITLE
How to reproduce Table 1

### ISSUE THREAD

**Issue by jameszhou-gl** [VectorInstitute/odyssey#79]
Hi authors, nice work! I was wondering how to run the code and reproduce Table 1 in MambaEHR paper? Could you please provide a detailed instruction for your code? Thank you so much!

**Comment by Adibvafa** [comment]
Hello, Thank you for your interest in our work!

Please follow these steps to reproduce the experiments done in Table 1:

**Dataset**
You need to have access to the MIMIC-IV-FHIR dataset from https://physionet.org/content/mimic-iv-fhir/1.0/
Use `collect.py` from `odyssey.data.mimiciv` to download patient information of MIMIC-IV-FHIR dataset.
Then, use the `generator.py` from `odyssey.data.seq` to create vocabulary, aggregate patient data and generate patient sequences.
Finally, you can see the examples in `DataProcessor.ipynb` from `odyssey.data` to prepare datasets with custom labels as well as patient splits for train, val, and test. For example, EHRMamba is finetuned on a `multi_dataset` as it contains all downstream labels.

**Training**
Use `pretrain.py` and `finetune.py` to train the model. You can find detailed slurm requests in https://github.com/VectorInstitute/odyssey/blob/main/slurm_scripts.md
Your `data-dir` should containt `sequence-file`, the parquet patient sequences, and `id-file` the pkl file with patient split information. The `vocab-dir` uses the directory of json files you saved from `generator.py`

**Evaluation**
The training scripts also evaluate the model on test data. To do seeded testing, you can run them with different seeds.
The XGBoost and Bi-LSTM models can be trained and evaluated using notebooks inside `odyssey.models.baseline`.

Please let us know if you run into any issues. Happy to help!

**Comment by 2533245542** [comment]
Hi,

Here are some steps I did before running `python odyssey/odyssey/data/mimiciv/collect.py`

in `odyssey` folder,

```
pip install poetry
poetry install
```

and I got error

```
Traceback (most recent call last):
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3302, in raw_connection
    return self.pool.connect()
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
    self._dec_overflow()
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 621, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jupyter/20000360102458359xu/Weipeng/reproduce_ehrmamba/odyssey/odyssey/data/mimiciv/collect.py", line 720, in <module>
    collector.get_patient_data()
  File "/home/jupyter/20000360102458359xu/Weipeng/reproduce_ehrmamba/odyssey/odyssey/data/mimiciv/collect.py", line 222, in get_patient_data
    results = self.execute_query(DATA_COLLECTION_CONFIG[PATIENT]["table_name"])
  File "/home/jupyter/20000360102458359xu/Weipeng/reproduce_ehrmamba/odyssey/odyssey/data/mimiciv/collect.py", line 202, in execute_query
    table = Table(
  File "<string>", line 2, in __new__
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 427, in __new__
    return cls._new(*args, **kw)
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 482, in _new
    metadata._remove_table(name, schema)
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 477, in _new
    table.__init__(name, metadata, *args, _no_init=False, **kw)
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 857, in __init__
    self._autoload(
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 887, in _autoload
    insp = inspection.inspect(autoload_with)
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/inspection.py", line 140, in inspect
    ret = reg(subject)
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 312, in _engine_insp
    return Inspector._construct(Inspector._init_engine, bind)
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 245, in _construct
    init(self, bind)
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 256, in _init_engine
    engine.connect().close()
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3278, in connect
    return self._connection_cls(self)
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 148, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2442, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3302, in raw_connection
    return self.pool.connect()
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
    self._dec_overflow()
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 621, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/home/jupyter/miniconda3/envs/water/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

Do you have any idea?
